const categories={automobile:{label:'01 / AUTOMOBILES',ending:'BY DESIGN.',headline:'EXCEPTIONAL.<br>BY LAND.<br><span>BY DESIGN.</span>',caption:'THE ART OF ARRIVAL',title:'The road, reimagined.',copy:'From sculpted grand tourers to uncompromising performance cars, discover an expression of engineering that reflects your own. Begin with the journey you want to take.',points:['Grand touring','Performance','Bespoke specification'],interest:'Automobiles',alt:'Silver grand touring coupe outside a modern coastal residence'},yacht:{label:'02 / YACHTS',headline:'EXCEPTIONAL.<br>BY SEA.<br><span>BY NATURE.</span>',caption:'BEYOND THE HORIZON',title:'Your own latitude.',copy:'Quiet coves. Long passages. Days that follow no one’s schedule but yours. Explore a yachting brief shaped around your destinations, your guests and the way you want to spend your time.',points:['Motor yachts','Life on board','Mediterranean escapes'],interest:'Yachts',alt:'White superyacht on turquoise Mediterranean waters'},aviation:{label:'03 / PRIVATE AVIATION',headline:'EXCEPTIONAL.<br>BY AIR.<br><span>BY CHOICE.</span>',caption:'A WORLD WITHIN REACH',title:'A world within reach.',copy:'Make room for the moments that matter. Consider private aviation around your typical routes, cabin preferences and travel rhythm, with a clear view of what you need from every flight.',points:['Business travel','Cabin comfort','Long-range journeys'],interest:'Private aviation',alt:'Private business jet on an airfield at dusk'}};
const dialog=document.querySelector('#detail');let selected='Automobiles';let detailCategory='automobile';
function chooseInterest(value){selected=value;document.querySelectorAll('[data-interest]').forEach(b=>{const active=b.dataset.interest===value;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
document.querySelectorAll('[data-interest]').forEach(b=>b.addEventListener('click',()=>chooseInterest(b.dataset.interest)));
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.category;const data=categories[key];document.querySelector('#hero-image').src=`assets/${key}.webp`;document.querySelector('#hero-image').alt=data.alt;document.querySelector('h1').innerHTML=data.headline;document.querySelector('#hero-caption').textContent=data.caption;document.querySelectorAll('[data-category]').forEach(t=>t.setAttribute('aria-selected',String(t===b)))}));
document.querySelector('.hero-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('[data-category]')];const index=tabs.indexOf(document.activeElement);const next=tabs[(index+(e.key==='ArrowRight'?1:2))%3];next.focus();next.click()});
document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{detailCategory=b.dataset.detail;const data=categories[detailCategory];document.querySelector('#detail-image').src=`assets/${detailCategory}.webp`;document.querySelector('#detail-image').alt=data.alt;document.querySelector('#detail-label').textContent=data.label;document.querySelector('#detail-title').textContent=data.title;document.querySelector('#detail-copy').textContent=data.copy;document.querySelector('#detail-points').replaceChildren(...data.points.map(text=>{const span=document.createElement('span');span.textContent=text;return span}));dialog.showModal()}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('#detail-enquire').addEventListener('click',()=>{chooseInterest(categories[detailCategory].interest);dialog.close();document.querySelector('#concierge').scrollIntoView({behavior:'smooth'});document.querySelector('#vision').focus({preventScroll:true})});
document.querySelector('.menu-toggle').addEventListener('click',e=>{const open=document.querySelector('nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open));e.currentTarget.textContent=open?'Close':'Menu'});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('nav').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');document.querySelector('.menu-toggle').textContent='Menu'}));
document.querySelector('#prepare').addEventListener('click',()=>{const vision=document.querySelector('#vision').value.trim();const text=`AUREL | PRIVATE COLLECTION\nYOUR PERSONAL BRIEF\n\nInterest: ${selected}\n\nYour vision:\n${vision||'An initial exploration of the collection.'}\n\nConsiderations for your advisor:\n- Preferred model or type\n- Intended use and destinations\n- Timing and budget\n- Essential features\n\nThis brief was prepared for you to keep or share. It has not been sent to an advisor.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='AUREL-private-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#brief-status').textContent='Your brief has been downloaded. You can share it with your advisor; nothing has been sent.'});
document.querySelector('#year').textContent=new Date().getFullYear();

document.querySelectorAll('[data-sale-category]').forEach(button=>button.addEventListener('click',()=>{window.location.href='listings.html?category='+encodeURIComponent(button.dataset.saleCategory)}));
