const inventory=[
{id:'AU-001',name:'Argent GT',category:'Automobiles',year:2025,price:285000,condition:'Pre-owned',location:'Monaco',region:'Europe',image:'automobile',summary:'A sculpted grand tourer imagined for long coastal drives. This sample listing demonstrates how an automobile can be presented in the AUREL sales collection.',specs:{'Mileage':'4,800 km','Transmission':'Automatic','Exterior':'Silver','Interior':'Black leather'},teaser:'4,800 km · Automatic · Silver'},
{id:'YA-001',name:'Horizon 48',category:'Yachts',year:2024,price:24500000,condition:'Pre-owned',location:'Antibes, France',region:'Europe',image:'yacht',summary:'An ocean-going motor yacht concept with generous deck spaces and an emphasis on private entertaining. This is illustrative inventory for the sales-page design.',specs:{'Length':'48 m','Guest cabins':'5','Guests':'10','Hull':'Displacement'},teaser:'48 m · 5 cabins · 10 guests'},
{id:'AV-001',name:'Meridian Executive',category:'Private aviation',year:2023,price:32000000,condition:'Pre-owned',location:'Miami, USA',region:'North America',image:'aviation',summary:'A business jet concept with a spacious executive cabin. The sample specification shows the information a buyer could compare before contacting a seller.',specs:{'Flight hours':'850 h','Passenger seats':'12','Cabin':'Executive','Aircraft type':'Business jet'},teaser:'850 flight hours · 12 seats · Executive cabin'},
{id:'AU-002',name:'Argent GT Signature',category:'Automobiles',year:2026,price:365000,condition:'New',location:'Dubai, UAE',region:'Middle East',image:'automobile',summary:'A new grand touring concept with a bespoke interior brief. Concept imagery is shared with the Argent GT; actual listing photography can be added when inventory is supplied.',specs:{'Mileage':'Delivery mileage','Transmission':'Automatic','Exterior':'Silver','Interior':'Bespoke specification'},teaser:'New · Automatic · Bespoke interior'},
{id:'YA-002',name:'Horizon 52 Reserve',category:'Yachts',year:2026,price:34500000,condition:'New',location:'Viareggio, Italy',region:'Europe',image:'yacht',summary:'A larger motor yacht concept designed around relaxed cruising and time with guests. Sample figures and concept imagery are for demonstration only.',specs:{'Length':'52 m','Guest cabins':'6','Guests':'12','Hull':'Displacement'},teaser:'52 m · 6 cabins · 12 guests'},
{id:'AV-002',name:'Meridian Global',category:'Private aviation',year:2025,price:48500000,condition:'Pre-owned',location:'London, UK',region:'Europe',image:'aviation',summary:'A private aviation concept for an international travel schedule. This sample record provides a starting point for real aircraft photography and seller-verified specifications.',specs:{'Flight hours':'220 h','Passenger seats':'14','Cabin':'Executive','Aircraft type':'Business jet'},teaser:'220 flight hours · 14 seats · Executive cabin'}
];
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);let category='all';let activeListing=null;
function filteredInventory(){const query=$('#search').value.trim().toLowerCase();const max=$('#price').value;const rows=inventory.filter(x=>(category==='all'||x.category===category)&&(!query||[x.name,x.location,x.id,x.category].join(' ').toLowerCase().includes(query))&&($('#condition').value==='all'||x.condition===$('#condition').value)&&($('#region').value==='all'||x.region===$('#region').value)&&(max==='all'||(max==='over'?x.price>25000000:x.price<=Number(max))));const sort=$('#sort').value;if(sort==='low')rows.sort((a,b)=>a.price-b.price);if(sort==='high')rows.sort((a,b)=>b.price-a.price);if(sort==='newest')rows.sort((a,b)=>b.year-a.year);return rows}
function render(){const rows=filteredInventory();$('#result-count').textContent=`${rows.length} ${rows.length===1?'listing':'listings'} · Prices in USD`;$('#empty').hidden=rows.length>0;$('#listing-grid').innerHTML=rows.map(x=>`<article class="sale-card"><div class="sale-image"><img src="assets/${x.image}.webp" alt="${x.name} concept image" loading="lazy"><span class="tag">${x.condition.toUpperCase()}</span><span class="sample">CONCEPT IMAGE</span></div><div class="sale-info"><div class="sale-meta"><span>${x.category.toUpperCase()}</span><span>${x.year} / ${x.id}</span></div><h2>${x.name}</h2><p class="sale-specs">${x.teaser}</p><p class="sale-price">${money(x.price)}<small>USD</small></p><div class="sale-bottom"><span>${x.location}</span><button data-listing="${x.id}" aria-label="View ${x.name} listing">View listing +</button></div></div></article>`).join('')}
function reset(){category='all';$('#search').value='';for(const id of ['price','condition','region'])$('#'+id).value='all';$('#sort').value='featured';document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category==='all')));render()}
function showListing(id){const x=inventory.find(x=>x.id===id);if(!x)return;activeListing=x;$('#listing-photo').src=`assets/${x.image}.webp`;$('#listing-photo').alt=x.name+' concept image';$('#listing-meta').textContent=x.category.toUpperCase()+' / '+x.id;$('#listing-title').textContent=x.name;$('#listing-price').textContent=money(x.price)+' USD';$('#listing-description').textContent=x.summary;$('#specifications').replaceChildren(...Object.entries({Year:x.year,Condition:x.condition,Location:x.location,...x.specs}).map(([key,value])=>{const div=document.createElement('div');const dt=document.createElement('dt');dt.textContent=key;const dd=document.createElement('dd');dd.textContent=value;div.append(dt,dd);return div}));$('#inquiry-status').textContent='';$('#listing-detail').showModal()}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));render()}));for(const id of ['search','price','condition','region','sort'])$('#'+id).addEventListener(id==='search'?'input':'change',render);$('#reset').addEventListener('click',reset);$('#empty-reset').addEventListener('click',reset);$('#listing-grid').addEventListener('click',e=>{const b=e.target.closest('[data-listing]');if(b)showListing(b.dataset.listing)});$('.dialog-close').addEventListener('click',()=>$('#listing-detail').close());$('#listing-detail').addEventListener('click',e=>{const d=$('#listing-detail');if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()});
$('#download-enquiry').addEventListener('click',()=>{const x=activeListing;if(!x)return;const text=`AUREL | LISTING INQUIRY BRIEF\n\n${x.name} | ${x.id}\nCategory: ${x.category}\nYear: ${x.year}\nIndicative asking price: ${money(x.price)} USD\nLocation: ${x.location}\n${Object.entries(x.specs).map(([k,v])=>k+': '+v).join('\n')}\n\nQuestions for the seller:\n- Is this item available?\n- Can you provide verified specifications and ownership history?\n- Can I arrange an inspection or viewing?\n- What additional taxes, fees and delivery costs apply?\n\nDEMONSTRATION LISTING: Not a live offer for sale. This brief has not been sent; seller contact is not connected.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`AUREL-${x.id}-inquiry.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#inquiry-status').textContent='Inquiry brief downloaded. Nothing has been sent to a seller.'});$('.menu-toggle').addEventListener('click',()=>{const open=$('nav').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(open));$('.menu-toggle').textContent=open?'Close':'Menu'});render();

const initialCategory=new URLSearchParams(location.search).get('category');if(['Automobiles','Yachts','Private aviation'].includes(initialCategory)){category=initialCategory;document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));render()}
